spring.application.name=Opored

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

# Security config
security.jwt.private.key=${JWT_PRIVATE_KEY}
security.jwt.user.generator=AUTH0JWT-GENERATOR


# Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=announcementsGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.template.default-topic=announcements-topic


# Swagger config
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.resolve-schema-properties=false
springdoc.swagger-ui.default-models-expand-depth=0
springdoc.swagger-ui.default-model-expand-depth=0
springdoc.swagger-ui.display-request-duration=true

# File storage
file.storage.upload.dir=/storage/uploads

# Max file size (image, video, document)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB