package com.acasado.opored.enumeration;

public enum PermissionEnum {
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    STUDENT_READ,
    STUDENT_CREATE,
    STUDENT_UPDATE,
    STUDENT_DELETE,
    MODERATION_READ,
    MODERATION_CREATE,
    MODERATION_UPDATE,
    MODERATION_DELETE,
    ADMINISTRATION_READ,
    ADMINISTRATION_CREATE,
    ADMINISTRATION_UPDATE,
    ADMINISTRATION_DELETE,
    PROFESSOR_READ,
    PROFESSOR_CREATE,
    PROFESSOR_UPDATE,
    PROFESSOR_DELETE,
    ROOT
}
